###create admin
POST http://localhost:3000/user/admin
content-type: application/json

{
  "dni": "11111111",
  "name": "admin",
  "lastName": "comun",
  "email": "loaslza@gmail.com",
  "password": "123456S*",
  "birthdate": "2005-01-01",
  "notification": false
}