###create client
POST http://localhost:3000/client
content-type: application/json

{
  "dni": "466",
  "name": "Juan",
  "lastName": "Perez",
  "email": "lolapal1uz1a@gmail.com",
  "password": "123456S*",
  "birthdate": "2005-01-01",
  "notification": false
}
